# Generated by Django 3.2.8 on 2021-11-10 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidoPT', models.CharField(max_length=50)),
                ('apellidoMT', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('tp_licencia', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductors',
            },
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('nr_serie', models.CharField(max_length=50)),
                ('tp_combustible', models.CharField(max_length=50)),
                ('tp_maquinaria', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquinarias.conductor')),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Maquinarias',
            },
        ),
    ]
